## baiduPush.yml
name: 'baiduPush'

on:
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  my-first-job:
    name: my first job
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      
    - name: set up go
      uses: actions/setup-go@v5
      with:
        go-version: 1.20.6
        
    - name: 'Run main.go' # 步骤二，执行sh命令文件
      run: go run main.go

    - name: 'get DATE' # 步骤二，执行sh命令文件
      run: timedatectl && date
